name: Portfolio CI

on:
  push:
    branches:
      - PortfolioBranchV1
    paths:
      - "**/*.html"
      - "templates/**"
      - "projects.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project (HTML + Tailwind CSS)
        run: npm run build

      - name: Verify output
        run: ls -R

      - name: Check secret exists
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret is missing"
          else
            echo "Secret is set"
          fi
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
